### ISSUE TITLE
deciding between int and uint

### ISSUE THREAD

**Issue by fabianocorsetti** [ElectronicStructureLibrary/libescdf#1]
Generally, `escdf_geometry` treats integer variables as ints, while `escdf_grid_scalarfields` treats them as uints. There are also some repeated variables for the two groups (`number_of_physical_dimensions`, `dimension_types`), which at the moment do not agree on type. This is important because whatever we decide needs to go in the ESCDF standard specifications on the wiki (at the moment, everything is listed as int).

My suggestion is that variables with physical significance which are restricted to being positive should be uints (e.g., `number_of_physical_dimensions`), while variables without physical significance should be kept as ints, even if for the moment only positive values are allowed (e.g., `dimension_types `). This would allow people more flexibility to extend the definition to suit their needs.

Note that there also exist integer variables with physical significance that need to be ints (e.g., `cell_in_host` in the geometry specs).

**Comment by dcaliste** [comment]
> My suggestion is that variables with physical significance which are restricted to being positive should be uints (e.g., number_of_physical_dimensions), while variables without physical significance should be kept as ints, even if for the moment only positive values are allowed

I fully agree even if I didn't implement it like that. I'll update as soon as we agree on what is what.

**Comment by fabianocorsetti** [comment]
> I fully agree even if I didn't implement it like that. I'll update as soon as we agree on what is what.

Great. I'll update the wiki page on geometry and you can see if you agree with the specs.

**Comment by fabianocorsetti** [comment]
I have updated the wiki pages on geometries and densities.

**Comment by dcaliste** [comment]
Thank you Fabiano, I'll update grid scalarfield later today or on Monday (I've a meeting all tomorrow).

**Comment by dcaliste** [comment]
Ok, grid scalarfield is now using int when mentioned in the specs.

**Comment by micaeljtoliveira** [comment]
I also agree with Fabiano's suggestion.
