### ISSUE TITLE
Ancestral autotools

### ISSUE THREAD

**Issue by dcaliste** [ElectronicStructureLibrary/libescdf#4]
I use Ubuntu 12.04 at work with older autotools versions than those mentioned in the configure.ac script. Namely, I have autoconf 2.68 and automake 1.11.

I've modified the configure.ac in my local copy with these lower versions and everything seems to work.

Do we have hard requirements on autoconf 2.69 and automake 1.13 or can we downgrade the requirements to those mentioned earlier ?

**Comment by pouillon** [comment]
Fine with me. Most of the bugfixes in more recent versions are related to Fortran and are only necessary for this language. Please note that I'll separate the build system of the Fortran interfaces soon.

**Comment by dcaliste** [comment]
We'll upgrade to latest Ubuntu in May or June this year.
